services:
  postgresql:
    container_name: postgresql
    image: postgres:15
    ports:
      - "5432:5432"
    networks:
      - batch_network
    volumes:
      - challenge_postgresql_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_DB}"

  banking-service:
    image: jarana26/banking-transaction-service:1.0 #Public Repo
    container_name: banking-service
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    networks:
      - batch_network
    environment:
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
      SPRING_DATASOURCE_USERNAME: "${POSTGRES_USER}"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD}"
      JAVA_OPTS: "${JAVA_OPTS}"

    restart: always

volumes:
  challenge_postgresql_data:
    driver: local

networks:
  batch_network:
    driver: bridge
